from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional


class IncidentInput(BaseModel):
    """Input received when a new incident is reported."""

    incident_type: str = Field(
        ...,
        description="Type of incident: emergency_911, traffic_sensor, manual_report",
    )
    description: str = Field(..., description="Free text description of the incident")
    location: Dict[str, float] = Field(
        ..., description="Coordinates mapping containing 'lat' and 'lng'"
    )
    current_time: str = Field(..., description="ISO 8601 timestamp")
    base_eta_to_destination: int = Field(
        ..., description="Baseline travel time to destination in minutes"
    )


class IncidentClassification(BaseModel):
    """Output from the Perception Agent classifying the incident."""

    incident_type: str = Field(
        ..., description="Classified incident type: medical_emergency, accident, hazard"
    )
    severity: str = Field(
        ..., description="Classified severity: critical, major, minor"
    )
    location: Dict[str, float] = Field(..., description="Target location coordinates")
    baseline_eta: int = Field(
        ..., description="Estimated travel time in minutes without optimization"
    )
    priority_score: float = Field(
        ..., description="Priority coefficient from 0.0 to 1.0"
    )
    reasoning: str = Field(..., description="Classification logic explanation")


class OrchestratorInput(BaseModel):
    """Input parameters for the Orchestrator Agent sequential coordinator."""

    incident_classification: IncidentClassification
    current_city_state: Dict[str, Any] = Field(
        ..., description="Current weather, active blockages, closures"
    )


class RouteAgentInput(BaseModel):
    """Input parameters provided to Route Agents for routing proposals."""

    incident_location: Dict[str, float]
    destination: Dict[str, float]
    current_traffic_conditions: Dict[str, str]
    objectives: Dict[str, str]


class RouteProposal(BaseModel):
    """Output routing proposal generated by a Route Agent."""

    agent_id: str = Field(..., description="Identifier of proposing agent")
    recommended_route: str = Field(..., description="Proposed corridor name")
    ambulance_eta: int = Field(
        ..., description="Estimated ambulance travel time in minutes"
    )
    vehicles_impacted: int = Field(
        ..., description="Estimate of delayed non-emergency vehicles"
    )
    avg_delay_per_vehicle: int = Field(
        ..., description="Average delay added in minutes"
    )
    safety_score: float = Field(..., description="Safety index from 0.0 to 1.0")
    reasoning: str = Field(..., description="Agent justification for proposal")
    confidence: float = Field(..., description="Confidence index from 0.0 to 1.0")


class OrchestratorDecision(BaseModel):
    """Final routing decision brief generated by Orchestrator Agent."""

    incident_id: str
    proposal_a: RouteProposal
    proposal_b: RouteProposal
    winner: str = Field(..., description="Winning agent id: route_a or route_b")
    requires_approval: bool
    reasoning_summary: str


class SimulationInput(BaseModel):
    """Input data sent to Simulation & Negotiation resolver."""

    proposal_a: RouteProposal
    proposal_b: RouteProposal
    incident: IncidentClassification


class NegotiationResult(BaseModel):
    """Resolution details from Simulation Agent negotiation."""

    winner: str
    score_a: float
    score_b: float
    margin: float
    reasoning: str
    heatmap_a_url: str
    heatmap_b_url: str
    counterfactual: Dict[str, Any]


class ExplainabilityInput(BaseModel):
    """Input for Explainability Agent to summarize decision reasons."""

    negotiation_result: NegotiationResult
    proposal_a: RouteProposal
    proposal_b: RouteProposal


class ExplainabilityOutput(BaseModel):
    """Operator friendly decision justification."""

    decision: str
    reasoning_one_liner: str
    counterfactual: str
    confidence: float
    approval_required: bool


class ApprovalGateInput(BaseModel):
    """Parameters evaluated by the Human Approval Gate workflow node."""

    incident_id: str
    decision: str
    reasoning: str
    impact_score: float
    timestamp: str
